<?php
declare(strict_types=1);

namespace Tecteb\Marketplace\Modules\Product\Infrastructure\Migrations;

use Tecteb\Marketplace\Contracts\DatabaseInterface;
use Tecteb\Marketplace\Contracts\MigrationInterface;
use Tecteb\Marketplace\Core\Exceptions\MigrationException;

/**
 * Two columns on `tmc_products`, each for a reason no existing column can serve.
 *
 * **`description` — the vendor's long description (§4).** Until now the form
 * had one text field, `short_description`, and WooCommerce's long description
 * was GENERATED by `WooCommerceProjector::storefrontDescription()` out of the
 * short description, the spec answers and the brand. The owner asked for two
 * independent fields, each bound to its own WooCommerce field, and there is no
 * column to put the second one in: `tmc_products` is one column per field, so
 * this is structural rather than convenient.
 *
 * `NULL` is the default and it is the whole compatibility story:
 *
 *  - `NULL`  — this row predates the field. Nobody has asked for anything, so
 *    the projector leaves WooCommerce's long description ALONE. That is the
 *    owner's «توضیحات کامل موجود در ووکامرس را با متن کوتاه یا متن تولیدی
 *    جایگزین نکن», and it is also what keeps a manager's hand-written text and
 *    their SEO safe on every product that already exists.
 *  - `''`    — the vendor cleared it on purpose. Written, and the storefront
 *    ends up empty, because an explicit clear is an instruction.
 *
 * No backfill. Copying the generated text into the column would turn text
 * nobody wrote into text the vendor appears to have written, and the next
 * approval would then write it over whatever the manager had — the same
 * «حدس نزن» rule migration 19 followed for the approved baseline.
 *
 * **`create_token` — one create per submitted form (§2).** A create had no
 * idempotency at all: a replayed POST (which is exactly what a browser does
 * after a request times out) or a double click made a second product. The
 * owner measured several products with the same name.
 *
 * A guard against that needs a UNIQUELY KEYED row — `alpha.40` learned this
 * for the money unit and it is the same shape here. Three alternatives were
 * weighed:
 *
 *  - a token ledger in user meta or a transient — storage that expires and
 *    that `FlashStoreInterface::take()` reads destructively, so the SECOND
 *    replay creates a duplicate again;
 *  - matching on «same vendor, same title, a few seconds ago» — a guess, and
 *    one that would refuse the vendor who deliberately wants two products of
 *    the same name, which the owner explicitly requires to keep working;
 *  - a transaction around the create — the two requests are two requests, and
 *    no isolation level makes the second one see the first's uncommitted row.
 *
 * So: `VARCHAR(64) NULL` with `UNIQUE KEY (vendor_user_id, create_token)`.
 * **Nullable is load-bearing**: MySQL lets NULL repeat in a unique index, so
 * every legacy row and every create that carries no token keeps NULL and
 * cannot collide — the same property `create()` already relies on for
 * `wc_product_id`. A deliberate second product comes from a freshly rendered
 * form with a fresh token and is created normally.
 *
 * **Rolling back to `alpha.40` needs no database work.** Both columns are
 * additive and nothing older names them; `alpha.40` reads neither. The cost is
 * stated in `docs/upgrade-and-rollback.md` §24 and it is the two defects
 * coming back, not data loss.
 */
final class M0023ProductDescriptionAndCreateToken implements MigrationInterface
{
    public const PRODUCTS = 'tmc_products';
    public const DESCRIPTION = 'description';
    public const CREATE_TOKEN = 'create_token';
    public const TOKEN_INDEX = 'tmc_product_create_token';

    public function version(): int
    {
        return 23;
    }

    public function id(): string
    {
        return '0023_product_description_and_create_token';
    }

    public static function table(DatabaseInterface $db, string $suffix): string
    {
        return $db->prefix() . $suffix;
    }

    public function up(DatabaseInterface $db): void
    {
        $table = self::table($db, self::PRODUCTS);
        // Asked, not assumed, and read in THREE states — `alpha.38`'s rule. A
        // failed read answers `null`, which casts to nought, which would read
        // as «the column is not there» and send an `ALTER` that then fails on
        // a resume. `0` is a valid answer and means the column really is
        // missing.
        foreach ([self::DESCRIPTION, self::CREATE_TOKEN] as $column) {
            $has = $db->getVar(
                'SELECT COUNT(*) FROM information_schema.COLUMNS
                 WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s',
                [$table, $column]
            );
            if ($has === null) {
                throw new MigrationException(
                    'migration ' . $this->id() . ' failed asking for `' . $column . '`: ' . $db->lastError()
                );
            }
            if ((int) $has === 1) {
                continue;               // a resumed run; this half is done
            }
            $definition = $column === self::DESCRIPTION
                ? '`description` LONGTEXT NULL AFTER `short_description`'
                : '`create_token` VARCHAR(64) NULL AFTER `status`';
            $this->run($db, "ALTER TABLE `{$table}` ADD COLUMN {$definition}");
        }

        $hasIndex = $db->getVar(
            'SELECT COUNT(*) FROM information_schema.STATISTICS
             WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s',
            [$table, self::TOKEN_INDEX]
        );
        if ($hasIndex === null) {
            throw new MigrationException(
                'migration ' . $this->id() . ' failed asking for the token index: ' . $db->lastError()
            );
        }
        if ((int) $hasIndex === 0) {
            $this->run(
                $db,
                "ALTER TABLE `{$table}` ADD UNIQUE KEY `" . self::TOKEN_INDEX . '` (`vendor_user_id`, `create_token`)'
            );
        }
    }

    /**
     * The SHAPE, not the existence — `alpha.37`'s rule.
     *
     * Both columns AND the unique index are named. An `ADD COLUMN` that
     * succeeded while the `ADD UNIQUE KEY` did not would leave the token
     * column with no guard behind it, and a step reporting «complete» there
     * moves the schema onto a build whose whole idempotency claim is false.
     */
    public function verify(DatabaseInterface $db): bool
    {
        $table = self::table($db, self::PRODUCTS);
        $columns = $db->getVar(
            'SELECT COUNT(*) FROM information_schema.COLUMNS
             WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME IN (%s, %s)',
            [$table, self::DESCRIPTION, self::CREATE_TOKEN]
        );
        if ((int) $columns !== 2) {
            return false;
        }
        // Unique, and over both columns in this order: a non-unique index of
        // the same name would satisfy «an index exists» and guard nothing.
        $index = $db->getRow(
            'SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS cols, MAX(NON_UNIQUE) AS non_unique
               FROM information_schema.STATISTICS
              WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s',
            [$table, self::TOKEN_INDEX]
        );
        if ($index === null) {
            return false;
        }
        return (string) ($index['cols'] ?? '') === 'vendor_user_id,create_token'
            && (int) ($index['non_unique'] ?? 1) === 0;
    }

    /** `execute()` answers with a row count, and a successful DDL affects none (`alpha.8`). */
    private function run(DatabaseInterface $db, string $sql): void
    {
        if ($db->execute($sql) === null) {
            throw new MigrationException(
                'migration ' . $this->id() . ' failed: ' . $db->lastError() . ' — ' . $sql
            );
        }
    }
}
