#!/usr/bin/env bash
# The index of everything that is NOT in git any more.
#
# The binary evidence — screenshots, walkthrough video — and the two large
# archives moved to release attachments, because a 1.4 GB repository is one
# nobody can clone and GitHub already warns about every push. Source, tests,
# text reports and hashes stayed behind.
#
# Moving them out is only safe if nothing becomes unverifiable on the way. So
# this writes a plain-text index, committed to git, naming every file that
# left, its size and its SHA-256, and the attachment it now lives in. A
# reader can download the attachment and check any file against this list
# without trusting either the attachment or this repository.
#
# Nothing is deleted. The files stay on disk, stay in the archives, and stay
# in the history they were already committed to — this is a change to what
# FUTURE commits carry, not a removal of anything.
#
#   bash tools/evidence-manifest.sh [output]
set -u
OUT="${1:-docs/evidence-manifest.txt}"
# Same reason as reviewable-bundle.sh: a throwaway build must hash the archive
# IT made, not the delivered one sitting in the real dist/.
DIST="${TMC_DIST:-dist}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

VERSION="$(grep -m1 '^ \* Version:' tecteb-marketplace-core.php | awk '{print $3}')"

# How many files the index being replaced already names. Read BEFORE anything
# is written, because this guard is about what would be lost.
#
# **Why a shrink is refused.** `alpha.38` was built in a container that is a
# fresh clone, and the image evidence is deliberately not in git (`alpha.22`)
# — so `find` matched three files instead of five hundred and twenty-nine and
# this script cheerfully replaced the record of everything the owner already
# holds with a three-line list. The existing guard only refused an EMPTY
# index, and three is not empty. The index is the ONLY record of files that
# are not in the repository; it may grow, and it may not quietly shrink.
PREVIOUS=0
if [ -f "${OUT}" ]; then
  PREVIOUS=$(grep -cE '^[0-9a-f]{64}  [0-9]+  docs/evidence/' "${OUT}" || echo 0)
fi

{
  echo "# What lives in the release attachments rather than in git"
  echo "#"
  echo "# Generated by tools/evidence-manifest.sh — do not hand-edit."
  echo "# Every line: <sha256>  <bytes>  <path>"
  echo "#"
  echo "plugin_version=${VERSION}"
  # Deliberately no timestamp. This file travels inside a HASHED archive, and
  # a clock reading would make every rebuild produce different bytes for an
  # unchanged tree — measured, and it did. The version identifies the release
  # this index belongs to; the date it was typed identifies nothing.
  echo

  echo "## attachment: ${VERSION} evidence archive (images and video)"
  echo "## every file below is inside tecteb-marketplace-core-evidence-${VERSION}.tar.gz"
  find docs/evidence -type f \
    \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \
       -o -iname '*.gif' -o -iname '*.pdf' -o -iname '*.webm' -o -iname '*.mp4' \) \
    | LC_ALL=C sort \
    | while IFS= read -r f; do
        printf '%s  %s  %s\n' "$(sha256sum "$f" | cut -c1-64)" "$(stat -c%s "$f")" "$f"
      done
  echo

  # Only the evidence archive. The source archive and the reviewable bundle
  # both CONTAIN this file, so hashing either here would change the thing
  # being hashed and the number would never settle — measured: two builds in
  # a row produced two different source-archive hashes for an unchanged tree.
  # Their hashes live in dist/SHA256SUMS, which is written after they exist.
  echo "## attachment: the image-and-video archive itself"
  for f in "${DIST}"/*-evidence-*.tar.gz; do
    [ -f "$f" ] || continue
    printf '%s  %s  %s\n' "$(sha256sum "$f" | cut -c1-64)" "$(stat -c%s "$f")" "$f"
  done
  echo

  echo "## still in git, and staying there"
  echo "# the installable package is small and byte-reproducible, and"
  echo "# tools/build.sh refuses to overwrite one that has been delivered —"
  echo "# a guard that only works while the bytes are somewhere it can check."
  for f in "${DIST}"/tecteb-marketplace-core-0*.zip; do
    [ -f "$f" ] || continue
    printf '%s  %s  %s\n' "$(sha256sum "$f" | cut -c1-64)" "$(stat -c%s "$f")" "$f"
  done
} > "${OUT}.new"

IMAGES=$(grep -cE '^[0-9a-f]{64}  [0-9]+  docs/evidence/' "${OUT}.new" || echo 0)
ARCHIVES=$(grep -cE '^[0-9a-f]{64}  [0-9]+  dist/' "${OUT}.new" || echo 0)

# An empty manifest means the find matched nothing, which on this repository
# means something is wrong — not that there is no evidence.
if [ "${IMAGES}" -le 0 ]; then
  rm -f "${OUT}.new"
  echo "manifest: NO evidence files matched — refusing to write an empty index" >&2
  exit 1
fi
if [ "${IMAGES}" -lt "${PREVIOUS}" ] && [ "${TMC_ALLOW_SHRINKING_MANIFEST:-0}" != "1" ]; then
  rm -f "${OUT}.new"
  echo "manifest: this tree has ${IMAGES} evidence files and the index already names ${PREVIOUS}." >&2
  echo "manifest: refusing to replace it — the index is the only record of files that are" >&2
  echo "manifest: NOT in git. Fetch the image evidence, or say so out loud with" >&2
  echo "manifest: TMC_ALLOW_SHRINKING_MANIFEST=1 and report what was dropped." >&2
  exit 1
fi
mv "${OUT}.new" "${OUT}"
echo "manifest: ${IMAGES} evidence files (was ${PREVIOUS}), ${ARCHIVES} archives → ${OUT}"
